---
title: "Introdução ao R: Parte I"
citeproc: true
menu: 
  class:
    parent: Class
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
---

## Leituras

Não há nenhuma leitura obrigatória para este primeira semana. Você deve  ler somente o Tutorial de Introdução ao R e praticas com os exercícios em sala de aula e de casa. 

No entanto, há vários materiais, tutoriais e cursos sobre R produzidos nos últimos anos, e aos interessados em aprender e praticar um pouco mais, coloco abaixo algumas sugestões. Este material é opcional, porém, quanto mais você praticar, mais rápido você se sentirá confortável em programmar em R. 

**Eu recomendo fortemente indicados o livro R for Data Science, sobretudo os  capítulos 4, 6 e 20.**

## Sugestões. 

#### [Swirl em R](https://swirlstats.com/): Tutorial Interativo sobre o uso do R. 

#### R Ambiente Programação
      
- [R for Data Science, Cap. 6: Scripts](https://r4ds.had.co.nz/workflow-scripts.html) 
- [R for Data Science, Cap 4: Workflow: Basics](https://r4ds.had.co.nz/workflow-basics.html) 
      
### Estrutura de Dados:

- [Tipo de Dados e Estrutura](https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/index.html). 
- [R For Data Science: Ch. 20: Vetores](https://r4ds.had.co.nz/vectors.html)
- [Data Carpentry: Data Subsetting](https://swcarpentry.github.io/r-novice-gapminder/06-data-subsetting/index.html) 
    
### Importando e Exportando Dados : 
- [R For Data Science.  Cap. 11: Importando Dados](https://r4ds.had.co.nz/data-import.html)

### Citação

[Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data. O’Reilly Media, Inc.](https://r4ds.had.co.nz/) 
