---
title: "Referências"
citeproc: true
menu: 
  class:
    parent: Class
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: false
editor_options: 
  chunk_output_type: console
---

Uma das coisas bonitas do R é a quantidade **ENORME** de recursos gratuitos disponíveis on-line para ajudar aqueles que estão aprendendo a programar.

Há também uma quantidade razoável de seminários como este com foco em Ciência Social Computacional, ou Introdução a Ciência de Dados. Assim como o nosso curso, a maior parte desses seminários deixa todos seus materiais disponíveis on-line. Diversos dos materiais e idéias deste nosso curso foram inspirados por estas experiências anteriores. Seguem abaixo alguns exemplos:


### [Summer Institute in Computacional Social Science](https://sicss.io/) por Mathew Salganik and Chris Bail.

Um programa de verão com duas semanas intensivas de treino e pesquisa em CSS. Eu participei desta escola em 2019, e todos seus materiais e vídeos estão disponíveis on-line. Eu irei sugerir alguns destes vídeos no decorrer do semestre. 


### [PLSC 31101: Computational Tools for Social Science](https://plsc-31101.github.io/course/) Universidade de Chicago, por Rochelle Therman.

Este curso é ministrado para alunos de mestrado e doutorado em Ciência Política na Universidade de Chicago. Foi criado por [Rochelle Terman](http://rochelleterman.com/) que é umas das pioneiras na construção destes cursos de introdução a CSS para alunos de pós graduação em Ciência Política. Vale a pena conferir os materiais deste curso. 

### [POIR 613 Computational Social Science](http://pablobarbera.com/POIR613/index.html) University of Southern California, por Pablo Barberá.

 Este curso é bastante parecido com o segundo módulo, com exemplos de CSS aplicada, do nosso curso. [Pablo Barberá](http://pablobarbera.com/) é um dos pioneiros em pesquisas com dados de Twitter na Ciênca Política. Sua pesquisa mais conhecida criou o método usado pela Folha de São Paulo nesta [ferramenta](https://temas.folha.uol.com.br/gps-ideologico/reta-ideologica-2020/a-posicao-ideologica-de-1-8-mil-influenciadores-no-twitter-em-2020.shtml) de aferir posições ideológicas com base em dados de Twitter. Vamos ler alguns artigos deles ao longo deste semestre.



### [Introduction to Data Science PPOL670](http://ericdunford.com/ppol670/) Georgetown University, por Eric Dunford

Este curso é mais focado para alunos de mestrado em Ciências de Dados e Políticas Públicas em Georgetown. [Eric Dunford](http://ericdunford.com/) é um excelente programador, e hoje é pesquisador de Georgetown e do Facebook. Fui colega de doutorado do Eric Dunford, e adoro seu estilo de programação. 

### [FLS 6397 - Introdução à Programação e Ferramentas Computacionais para as Ciências Sociais](https://github.com/leobarone/FLS6397_2018) por Leo Barone e Jonhatan Phillips. 

Curso mais focado em programação em R, totalmente em Português, e ministrado pelo Leonardo Barone, um dos pioneiros em uso do R nas ciências sociais brasileiras. 





